image:
  file: .gitpod.Dockerfile
tasks:
  - init: |
      ./gitpod-init.sh
    command: |
      ./gitpod-command.sh
ports:
  - port: 8000
    onOpen: open-browser
  - port: 8081
    onOpen: open-browser
  - port: 5432
    onOpen: ignore
vscode:
  extensions:
    - github.vscode-pull-request-github
    - cweijan.vscode-database-client2
